<?php

return [
    // Languages
    'PHP',
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'Go',
    'Rust',
    'Kotlin',
    'Swift',
    'Objective-C',
    'Scala',
    'Perl',
    'R',

    // Frameworks
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'Yii',
    'Zend Framework',
    'Phalcon',
    'CakePHP',
    'Slim',
    'Lumen',
    'React',
    'Vue.js',
    'Angular',
    'Ember.js',
    'Backbone.js',
    'Meteor',
    'Polymer',
    'Aurelia',
    'Django',
    'Flask',
    'Spring',
    'ASP.NET',
    'Ruby on Rails',
    'Sinatra',
    'Express.js',
    'Koa.js',
    'Hapi.js',

    // Libraries
    'jQuery',
    'Lodash',
    'Underscore.js',
    'Moment.js',
    'RxJS',
    'Async.js',
    'axios',
    'D3.js',
    'Three.js',
    'Immutable.js',
    'Modernizr',
    'NumPy',
    'Pandas',
    'Matplotlib',
    'SciPy',

    // Tools
    'NPM',
    'Yarn',
    'Webpack',
    'Babel',
    'Gulp',
    'Grunt',
    'Browserify',
    'Sass',
    'Less',
    'PostCSS',
    'ESLint',
    'Mocha',
    'Jasmine',
    'Protractor',
    'Jest',
    'Enzyme',
    'Docker',
    'Kubernetes',
    'Ansible',
    'Terraform',
    'Jenkins',
    'Travis CI',
    'CircleCI',
    'Git',
    'SVN',
    'Mercurial',

    // Areas of Development
    'Frontend',
    'Backend',
    'Fullstack',
    'Mobile',
    'Desktop',
    'Embedded',
    'Game',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Augmented Reality',
    'Virtual Reality',
    'Blockchain',
    'Cybersecurity',
    'DevOps',
    'UI/UX',
    'Database',
    'Testing',
    'Performance',
    'Accessibility',
    'Internationalization',
    'SEO',
    'Documentation',
];
